name: PlatformIO CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Create credentials.h for build 
        run: cp src/credentials_template.h src/credentials.h

      - name: Build PlatformIO Project
        run: pio run

      - name: Copy binaries to /firmware
        run: bash copy_firmware.sh

      - name: List workspace directory
        run: ls -la

      - name: Upload binaries for use in release step if needed
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: firmware


  deploy_release:
#    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: firmware

      - name: List workspace directory
        run: ls -la

      - name: Create release and upload binary
        run: |
          ls firmware
#          gh release create v0.0.${{github.run_number}} firmware/*
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash